### PR TITLE
Feature/ff1 saves

### PR DESCRIPTION
**Pull request by JackQuincy**
Adding ability to parse character stats, equipped items.
Adding ability to parse inventory items.
Added a unit test to verify no data is lost on deserialize -> serialize.

Not in this PR. 
Changing known spells/understanding what spells are currently known. 
Understanding a characters ability list that will probably be needed to be able to change classes/jobs if we want to support that.

### CODE REVIEW

**Review by Anub1sR0cks — APPROVED** [review]
Thanks for putting in the time to sort the classes out. As long as serialization & deserialization is in working order, I'm good with the change.

**Comment by BladePoint** [comment]
Seems like you approved the pull request but didn't actually merge it?

**Comment by Anub1sR0cks** [comment]
> Seems like you approved the pull request but didn't actually merge it?

I was waiting on him to merge it, but I pushed it through anyway.

I have some free time that I can dedicate to improving the project.

**Comment by jquincy-manticore** [comment]
Wasn't there a different PR that came out that was much more full featured than mine. That is why I never merged it.

**Pull request merged**
